apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: your-image:tag
          envFrom:
            - configMapRef:
                name: my-configmap  # Replace with your ConfigMap name
          volumeMounts:
            - name: settings-volume
              mountPath: /path/to/mount/settings.yml  # Replace with the desired path inside the container
              subPath: settings.yml
      volumes:
        - name: settings-volume
          configMap:
            name: my-configmap  # Replace with your ConfigMap name
            items:
              - key: settings.yml
                path: settings.yml

