apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-name  # Replace with your desired ConfigMap name
data:
  settings.yml: |
    opegenie:
      enabled: false
    email:
      enabled: true
    groups:
    - name: prod
      emails:
         - reviceremail@gmail.com
         - reciver@yahoo.com
    - name: dev
      emails:
         - reviceremail@gmail.com
         - reciver@yahoo.com
    domains:
    - name: https://skywalks.in
      enabled: true
      timeout: 10
      skip_ssl: false
      frequency: 10
      group: dev
    - name: https://sky-meter.skywalks.in
      enabled: true
      timeout: 10
      skip_ssl: false
      frequency: 60
      group: dev
    - name: https://github.com
      enabled: true
      timeout: 10
      skip_ssl: false
      frequency: 60
      group: prod
    - name: https://githcccubs.com
      enabled: true
      timeout: 10
      skip_ssl: false
      frequency: 60
      group: prod
